/**
 * Where each builder field shows up on its design, top to bottom.
 *
 * GENERATED — do not edit by hand. Measured by scripts/field-order/measure.mjs:
 * every field of every design is filled with a unique marker, the design is
 * rendered in the builder's preview (tap-to-open designs are opened, and what
 * their cover shows counts as first), and the first place each marker appears
 * is recorded. Fields the page never shows as text (map and music links, RSVP
 * contacts) sit with their neighbours in the template's own field order.
 *
 * FIELD_ORDER sorts the builder's input boxes so they follow the design; a
 * design missing here keeps its field definition order. FIELD_POSITION is how
 * far down the page (0–1) each field appears, for the preview to follow along.
 * Re-run the script after adding a design or moving things in one.
 */

export const FIELD_ORDER: Record<string, readonly string[]> = {
  "anniversary": [
    "coupleNames",
    "years",
    "couplePhoto",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "message",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "baby-shower": [
    "hostNames",
    "motherName",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "motherPhoto",
    "message",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "birthday-champagne": [
    "invitedBy",
    "age",
    "celebrantName",
    "date",
    "time",
    "venue",
    "theme",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "guestNote",
    "schedule",
    "message",
    "giftNote",
    "rsvpPhone",
    "rsvpEmail",
    "celebrantPhoto",
    "galleryImages",
    "musicUrl",
    "rsvpBy"
  ],
  "birthday-gala": [
    "invitedBy",
    "celebrantName",
    "age",
    "envelopeLine",
    "theme",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "city",
    "events",
    "dressCode",
    "palette",
    "message",
    "story",
    "celebrantPhoto",
    "galleryImages",
    "musicUrl",
    "travel",
    "faq",
    "contacts",
    "rsvpPhone",
    "rsvpEmail",
    "giftNote",
    "registryUrl",
    "rsvpBy"
  ],
  "birthday-long-lunch": [
    "theme",
    "celebrantName",
    "age",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "guestNote",
    "schedule",
    "message",
    "invitedBy",
    "giftNote",
    "rsvpPhone",
    "rsvpEmail",
    "galleryImages",
    "musicUrl",
    "celebrantPhoto",
    "rsvpBy"
  ],
  "birthday-martini": [
    "theme",
    "date",
    "time",
    "celebrantName",
    "age",
    "venue",
    "schedule",
    "dressCode",
    "guestNote",
    "venueAddress",
    "mapsUrl",
    "message",
    "invitedBy",
    "giftNote",
    "rsvpPhone",
    "rsvpEmail",
    "celebrantPhoto",
    "galleryImages",
    "musicUrl",
    "rsvpBy"
  ],
  "birthday-mirrorball": [
    "date",
    "celebrantName",
    "age",
    "theme",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "guestNote",
    "schedule",
    "message",
    "invitedBy",
    "giftNote",
    "rsvpPhone",
    "rsvpEmail",
    "celebrantPhoto",
    "galleryImages",
    "musicUrl",
    "rsvpBy"
  ],
  "cinematic-night": [
    "brideName",
    "groomName",
    "date",
    "time",
    "venue",
    "message",
    "bridePhoto",
    "groomPhoto",
    "dressCode",
    "venueAddress",
    "mapsUrl",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "diwali-party": [
    "hostNames",
    "title",
    "date",
    "time",
    "venue",
    "message",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "eid-milan": [
    "hostNames",
    "title",
    "date",
    "time",
    "venue",
    "message",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "schedule",
    "galleryImages"
  ],
  "elegant-wedding": [
    "bridePhoto",
    "groomPhoto",
    "brideName",
    "groomName",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "message",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "first-birthday": [
    "age",
    "celebrantPhoto",
    "theme",
    "celebrantName",
    "parentNames",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "message",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "ganesh-chaturthi": [
    "idolImage",
    "tagline",
    "title",
    "subtitle",
    "hostNames",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "invocation",
    "message",
    "schedule",
    "pooja",
    "dressCode",
    "visarjanDate",
    "visarjanTime",
    "galleryImages",
    "sampleWishes",
    "musicUrl"
  ],
  "griha-pravesh": [
    "hostNames",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "hostPhoto",
    "message",
    "pooja",
    "schedule",
    "galleryImages"
  ],
  "haldi-mehendi": [
    "brideName",
    "groomName",
    "date",
    "mehendiDate",
    "time",
    "mehendiTime",
    "venue",
    "message",
    "venueAddress",
    "mapsUrl",
    "mehendiVenue",
    "dressCode",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "indian-birthday": [
    "celebrantPhoto",
    "celebrantName",
    "age",
    "theme",
    "time",
    "date",
    "venue",
    "message",
    "venueAddress",
    "mapsUrl",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "indian-engagement": [
    "partner1Photo",
    "partner2Photo",
    "partner1Name",
    "partner2Name",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "message",
    "schedule",
    "galleryImages"
  ],
  "indian-wedding": [
    "bridePhoto",
    "groomPhoto",
    "brideName",
    "groomName",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "message",
    "schedule",
    "galleryImages",
    "musicUrl"
  ],
  "kgf-wedding": [
    "groomName",
    "brideName",
    "date",
    "time",
    "venue",
    "message",
    "groomPhoto",
    "groomFamilyDetails",
    "bridePhoto",
    "brideFamilyDetails",
    "coupleStory",
    "galleryImages",
    "musicUrl",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "schedule"
  ],
  "luxury-wedding": [
    "brideName",
    "groomName",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "message",
    "bridePhoto",
    "groomPhoto",
    "sangeetTime",
    "sangeetVenue",
    "sangeetDate",
    "receptionTime",
    "receptionVenue",
    "whatsappNumber",
    "receptionDate",
    "mehendiTime",
    "mehendiVenue",
    "mehendiDate",
    "haldiTime",
    "haldiVenue",
    "haldiDate",
    "brideFamily",
    "groomFamily",
    "galleryImages",
    "musicUrl"
  ],
  "namakaran": [
    "babyPhoto",
    "babyGender",
    "parentNames",
    "babyName",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "message",
    "schedule",
    "galleryImages"
  ],
  "pooja-invite": [
    "hostNames",
    "poojaName",
    "date",
    "time",
    "venue",
    "pooja",
    "hostPhoto",
    "message",
    "schedule",
    "venueAddress",
    "mapsUrl",
    "galleryImages"
  ],
  "rakshabandhan": [
    "tagline",
    "title",
    "subtitle",
    "sisterName",
    "brotherName",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "heroImage",
    "story",
    "timeline",
    "galleryImages",
    "sampleWishes",
    "musicUrl"
  ],
  "retirement": [
    "honoreePhoto",
    "hostNames",
    "honoreeName",
    "milestone",
    "date",
    "time",
    "venue",
    "message",
    "schedule",
    "venueAddress",
    "mapsUrl",
    "galleryImages"
  ],
  "royal-deco": [
    "groomName",
    "brideName",
    "date",
    "time",
    "venue",
    "bridePhoto",
    "groomPhoto",
    "groomFamilyDetails",
    "brideFamilyDetails",
    "message",
    "coupleStory",
    "schedule",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "galleryImages",
    "musicUrl"
  ],
  "sangeet-night": [
    "date",
    "time",
    "venue",
    "message",
    "brideName",
    "groomName",
    "dressCode",
    "schedule",
    "galleryImages",
    "musicUrl",
    "venueAddress",
    "mapsUrl",
    "hashtag"
  ],
  "save-the-date": [
    "couplePhoto",
    "brideName",
    "groomName",
    "date",
    "venue",
    "city",
    "followNote",
    "websiteUrl",
    "musicUrl",
    "message"
  ],
  "signature-garden": [
    "couplePhoto",
    "brideName",
    "groomName",
    "destination",
    "mapsUrl",
    "date",
    "venue",
    "invocation",
    "brideParents",
    "groomParents",
    "time",
    "venueAddress",
    "bridePhoto",
    "groomPhoto",
    "message",
    "blessings",
    "dressCode",
    "events",
    "travel",
    "story",
    "galleryImages",
    "musicUrl",
    "faq",
    "contacts",
    "whatsappNumber",
    "rsvpBy",
    "hashtag",
    "livestreamUrl",
    "registryUrl"
  ],
  "signature-kalyanam": [
    "invocation",
    "brideName",
    "groomName",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "message",
    "couplePhoto",
    "bridePhoto",
    "brideParents",
    "groomPhoto",
    "groomParents",
    "blessings",
    "events",
    "story",
    "galleryImages",
    "musicUrl",
    "dressCode",
    "travel",
    "contacts",
    "whatsappNumber",
    "faq",
    "rsvpBy",
    "hashtag",
    "livestreamUrl"
  ],
  "signature-nikah": [
    "invocation",
    "brideName",
    "groomName",
    "date",
    "time",
    "venue",
    "venueAddress",
    "mapsUrl",
    "couplePhoto",
    "message",
    "bridePhoto",
    "brideParents",
    "groomPhoto",
    "groomParents",
    "blessings",
    "events",
    "story",
    "galleryImages",
    "musicUrl",
    "dressCode",
    "travel",
    "contacts",
    "whatsappNumber",
    "faq",
    "rsvpBy",
    "hashtag",
    "livestreamUrl"
  ],
  "signature-rajwada": [
    "invocation",
    "brideName",
    "groomName",
    "date",
    "time",
    "venue",
    "message",
    "couplePhoto",
    "bridePhoto",
    "brideParents",
    "groomPhoto",
    "groomParents",
    "blessings",
    "events",
    "story",
    "galleryImages",
    "musicUrl",
    "venueAddress",
    "mapsUrl",
    "dressCode",
    "travel",
    "contacts",
    "whatsappNumber",
    "faq",
    "rsvpBy",
    "hashtag",
    "livestreamUrl"
  ]
}

export const FIELD_POSITION: Record<string, Readonly<Record<string, number>>> = {
  "anniversary": {
    "coupleNames": 0.017,
    "years": 0.017,
    "couplePhoto": 0.145,
    "date": 0.285,
    "time": 0.298,
    "venue": 0.33,
    "venueAddress": 0.339,
    "mapsUrl": 0.339,
    "dressCode": 0.35,
    "message": 0.438,
    "schedule": 0.505,
    "galleryImages": 0.578,
    "musicUrl": 0.578
  },
  "baby-shower": {
    "hostNames": 0.075,
    "motherName": 0.093,
    "date": 0.159,
    "time": 0.173,
    "venue": 0.196,
    "venueAddress": 0.206,
    "mapsUrl": 0.206,
    "dressCode": 0.219,
    "motherPhoto": 0.319,
    "message": 0.394,
    "schedule": 0.481,
    "galleryImages": 0.543,
    "musicUrl": 0.543
  },
  "birthday-champagne": {
    "invitedBy": 0.033,
    "age": 0.04,
    "celebrantName": 0.056,
    "date": 0.119,
    "time": 0.132,
    "venue": 0.142,
    "theme": 0.19,
    "venueAddress": 0.248,
    "mapsUrl": 0.248,
    "dressCode": 0.267,
    "guestNote": 0.303,
    "schedule": 0.334,
    "message": 0.444,
    "giftNote": 0.469,
    "rsvpPhone": 0.469,
    "rsvpEmail": 0.469,
    "celebrantPhoto": 0.507,
    "galleryImages": 0.507,
    "musicUrl": 0.507,
    "rsvpBy": 0.613
  },
  "birthday-gala": {
    "invitedBy": 0,
    "celebrantName": 0,
    "age": 0,
    "envelopeLine": 0,
    "theme": 0.094,
    "date": 0.1,
    "time": 0.1,
    "venue": 0.1,
    "venueAddress": 0.1,
    "mapsUrl": 0.1,
    "city": 0.112,
    "events": 0.204,
    "dressCode": 0.282,
    "palette": 0.282,
    "message": 0.313,
    "story": 0.365,
    "celebrantPhoto": 0.388,
    "galleryImages": 0.432,
    "musicUrl": 0.432,
    "travel": 0.496,
    "faq": 0.517,
    "contacts": 0.539,
    "rsvpPhone": 0.539,
    "rsvpEmail": 0.539,
    "giftNote": 0.584,
    "registryUrl": 0.584,
    "rsvpBy": 0.647
  },
  "birthday-long-lunch": {
    "theme": 0.068,
    "celebrantName": 0.076,
    "age": 0.098,
    "date": 0.13,
    "time": 0.139,
    "venue": 0.139,
    "venueAddress": 0.286,
    "mapsUrl": 0.286,
    "dressCode": 0.321,
    "guestNote": 0.333,
    "schedule": 0.366,
    "message": 0.4,
    "invitedBy": 0.413,
    "giftNote": 0.435,
    "rsvpPhone": 0.435,
    "rsvpEmail": 0.435,
    "galleryImages": 0.464,
    "musicUrl": 0.464,
    "celebrantPhoto": 0.464,
    "rsvpBy": 0.62
  },
  "birthday-martini": {
    "theme": 0.049,
    "date": 0.064,
    "time": 0.064,
    "celebrantName": 0.11,
    "age": 0.122,
    "venue": 0.133,
    "schedule": 0.239,
    "dressCode": 0.259,
    "guestNote": 0.273,
    "venueAddress": 0.338,
    "mapsUrl": 0.338,
    "message": 0.42,
    "invitedBy": 0.431,
    "giftNote": 0.481,
    "rsvpPhone": 0.481,
    "rsvpEmail": 0.481,
    "celebrantPhoto": 0.506,
    "galleryImages": 0.507,
    "musicUrl": 0.507,
    "rsvpBy": 0.635
  },
  "birthday-mirrorball": {
    "date": 0.08,
    "celebrantName": 0.087,
    "age": 0.093,
    "theme": 0.129,
    "time": 0.136,
    "venue": 0.136,
    "venueAddress": 0.285,
    "mapsUrl": 0.285,
    "dressCode": 0.303,
    "guestNote": 0.344,
    "schedule": 0.422,
    "message": 0.461,
    "invitedBy": 0.473,
    "giftNote": 0.486,
    "rsvpPhone": 0.486,
    "rsvpEmail": 0.486,
    "celebrantPhoto": 0.53,
    "galleryImages": 0.552,
    "musicUrl": 0.552,
    "rsvpBy": 0.654
  },
  "cinematic-night": {
    "brideName": 0.044,
    "groomName": 0.067,
    "date": 0.129,
    "time": 0.138,
    "venue": 0.138,
    "message": 0.19,
    "bridePhoto": 0.246,
    "groomPhoto": 0.246,
    "dressCode": 0.382,
    "venueAddress": 0.417,
    "mapsUrl": 0.417,
    "schedule": 0.52,
    "galleryImages": 0.58,
    "musicUrl": 0.58
  },
  "diwali-party": {
    "hostNames": 0.077,
    "title": 0.098,
    "date": 0.119,
    "time": 0.119,
    "venue": 0.127,
    "message": 0.213,
    "venueAddress": 0.344,
    "mapsUrl": 0.344,
    "dressCode": 0.357,
    "schedule": 0.466,
    "galleryImages": 0.532,
    "musicUrl": 0.532
  },
  "eid-milan": {
    "hostNames": 0.122,
    "title": 0.139,
    "date": 0.157,
    "time": 0.157,
    "venue": 0.164,
    "message": 0.218,
    "venueAddress": 0.347,
    "mapsUrl": 0.347,
    "dressCode": 0.359,
    "schedule": 0.472,
    "galleryImages": 0.537
  },
  "elegant-wedding": {
    "bridePhoto": 0.034,
    "groomPhoto": 0.034,
    "brideName": 0.083,
    "groomName": 0.108,
    "date": 0.17,
    "time": 0.185,
    "venue": 0.208,
    "venueAddress": 0.216,
    "mapsUrl": 0.216,
    "dressCode": 0.228,
    "message": 0.277,
    "schedule": 0.355,
    "galleryImages": 0.435,
    "musicUrl": 0.435
  },
  "first-birthday": {
    "age": 0.015,
    "celebrantPhoto": 0.092,
    "theme": 0.143,
    "celebrantName": 0.154,
    "parentNames": 0.19,
    "date": 0.24,
    "time": 0.263,
    "venue": 0.293,
    "venueAddress": 0.303,
    "mapsUrl": 0.303,
    "message": 0.39,
    "schedule": 0.477,
    "galleryImages": 0.534,
    "musicUrl": 0.534
  },
  "ganesh-chaturthi": {
    "idolImage": 0.011,
    "tagline": 0.079,
    "title": 0.088,
    "subtitle": 0.1,
    "hostNames": 0.124,
    "date": 0.156,
    "time": 0.171,
    "venue": 0.194,
    "venueAddress": 0.201,
    "mapsUrl": 0.201,
    "invocation": 0.229,
    "message": 0.257,
    "schedule": 0.323,
    "pooja": 0.433,
    "dressCode": 0.452,
    "visarjanDate": 0.494,
    "visarjanTime": 0.502,
    "galleryImages": 0.597,
    "sampleWishes": 0.597,
    "musicUrl": 0.597
  },
  "griha-pravesh": {
    "hostNames": 0.111,
    "date": 0.165,
    "time": 0.174,
    "venue": 0.192,
    "venueAddress": 0.204,
    "mapsUrl": 0.204,
    "hostPhoto": 0.227,
    "message": 0.279,
    "pooja": 0.346,
    "schedule": 0.363,
    "galleryImages": 0.429
  },
  "haldi-mehendi": {
    "brideName": 0.019,
    "groomName": 0.019,
    "date": 0.114,
    "mehendiDate": 0.114,
    "time": 0.133,
    "mehendiTime": 0.133,
    "venue": 0.148,
    "message": 0.191,
    "venueAddress": 0.293,
    "mapsUrl": 0.293,
    "mehendiVenue": 0.41,
    "dressCode": 0.469,
    "schedule": 0.526,
    "galleryImages": 0.57,
    "musicUrl": 0.57
  },
  "indian-birthday": {
    "celebrantPhoto": 0.026,
    "celebrantName": 0.045,
    "age": 0.059,
    "theme": 0.121,
    "time": 0.155,
    "date": 0.156,
    "venue": 0.167,
    "message": 0.215,
    "venueAddress": 0.356,
    "mapsUrl": 0.356,
    "schedule": 0.516,
    "galleryImages": 0.58,
    "musicUrl": 0.58
  },
  "indian-engagement": {
    "partner1Photo": 0.026,
    "partner2Photo": 0.026,
    "partner1Name": 0.124,
    "partner2Name": 0.146,
    "date": 0.188,
    "time": 0.195,
    "venue": 0.21,
    "venueAddress": 0.217,
    "mapsUrl": 0.217,
    "dressCode": 0.228,
    "message": 0.275,
    "schedule": 0.335,
    "galleryImages": 0.378
  },
  "indian-wedding": {
    "bridePhoto": 0.117,
    "groomPhoto": 0.117,
    "brideName": 0.155,
    "groomName": 0.176,
    "date": 0.206,
    "time": 0.214,
    "venue": 0.238,
    "venueAddress": 0.247,
    "mapsUrl": 0.247,
    "dressCode": 0.258,
    "message": 0.321,
    "schedule": 0.381,
    "galleryImages": 0.432,
    "musicUrl": 0.432
  },
  "kgf-wedding": {
    "groomName": 0.039,
    "brideName": 0.066,
    "date": 0.129,
    "time": 0.141,
    "venue": 0.149,
    "message": 0.185,
    "groomPhoto": 0.253,
    "groomFamilyDetails": 0.277,
    "bridePhoto": 0.297,
    "brideFamilyDetails": 0.321,
    "coupleStory": 0.376,
    "galleryImages": 0.394,
    "musicUrl": 0.394,
    "venueAddress": 0.585,
    "mapsUrl": 0.585,
    "dressCode": 0.631,
    "schedule": 0.665
  },
  "luxury-wedding": {
    "brideName": 0,
    "groomName": 0,
    "date": 0,
    "time": 0,
    "venue": 0,
    "venueAddress": 0,
    "mapsUrl": 0,
    "message": 0,
    "bridePhoto": 0.054,
    "groomPhoto": 0.054,
    "sangeetTime": 0.281,
    "sangeetVenue": 0.287,
    "sangeetDate": 0.293,
    "receptionTime": 0.318,
    "receptionVenue": 0.324,
    "whatsappNumber": 0.324,
    "receptionDate": 0.33,
    "mehendiTime": 0.355,
    "mehendiVenue": 0.361,
    "mehendiDate": 0.367,
    "haldiTime": 0.441,
    "haldiVenue": 0.447,
    "haldiDate": 0.453,
    "brideFamily": 0.505,
    "groomFamily": 0.531,
    "galleryImages": 0.568,
    "musicUrl": 0.568
  },
  "namakaran": {
    "babyPhoto": 0.039,
    "babyGender": 0.039,
    "parentNames": 0.106,
    "babyName": 0.137,
    "date": 0.174,
    "time": 0.183,
    "venue": 0.183,
    "venueAddress": 0.316,
    "mapsUrl": 0.316,
    "message": 0.416,
    "schedule": 0.49,
    "galleryImages": 0.545
  },
  "pooja-invite": {
    "hostNames": 0.022,
    "poojaName": 0.05,
    "date": 0.147,
    "time": 0.158,
    "venue": 0.158,
    "pooja": 0.197,
    "hostPhoto": 0.241,
    "message": 0.288,
    "schedule": 0.375,
    "venueAddress": 0.44,
    "mapsUrl": 0.44,
    "galleryImages": 0.563
  },
  "rakshabandhan": {
    "tagline": 0.011,
    "title": 0.068,
    "subtitle": 0.085,
    "sisterName": 0.103,
    "brotherName": 0.103,
    "date": 0.123,
    "time": 0.134,
    "venue": 0.147,
    "venueAddress": 0.157,
    "mapsUrl": 0.157,
    "heroImage": 0.189,
    "story": 0.322,
    "timeline": 0.396,
    "galleryImages": 0.473,
    "sampleWishes": 0.473,
    "musicUrl": 0.473
  },
  "retirement": {
    "honoreePhoto": 0.032,
    "hostNames": 0.075,
    "honoreeName": 0.096,
    "milestone": 0.113,
    "date": 0.14,
    "time": 0.153,
    "venue": 0.153,
    "message": 0.314,
    "schedule": 0.384,
    "venueAddress": 0.458,
    "mapsUrl": 0.458,
    "galleryImages": 0.583
  },
  "royal-deco": {
    "groomName": 0.047,
    "brideName": 0.069,
    "date": 0.115,
    "time": 0.148,
    "venue": 0.155,
    "bridePhoto": 0.2,
    "groomPhoto": 0.2,
    "groomFamilyDetails": 0.252,
    "brideFamilyDetails": 0.284,
    "message": 0.372,
    "coupleStory": 0.448,
    "schedule": 0.508,
    "venueAddress": 0.558,
    "mapsUrl": 0.558,
    "dressCode": 0.582,
    "galleryImages": 0.671,
    "musicUrl": 0.671
  },
  "sangeet-night": {
    "date": 0.143,
    "time": 0.15,
    "venue": 0.16,
    "message": 0.204,
    "brideName": 0.217,
    "groomName": 0.217,
    "dressCode": 0.318,
    "schedule": 0.318,
    "galleryImages": 0.375,
    "musicUrl": 0.375,
    "venueAddress": 0.554,
    "mapsUrl": 0.554,
    "hashtag": 0.639
  },
  "save-the-date": {
    "couplePhoto": 0.018,
    "brideName": 0.056,
    "groomName": 0.069,
    "date": 0.102,
    "venue": 0.192,
    "city": 0.203,
    "followNote": 0.219,
    "websiteUrl": 0.219,
    "musicUrl": 0.219,
    "message": 0.28
  },
  "signature-garden": {
    "couplePhoto": 0,
    "brideName": 0,
    "groomName": 0,
    "destination": 0,
    "mapsUrl": 0,
    "date": 0,
    "venue": 0,
    "invocation": 0,
    "brideParents": 0,
    "groomParents": 0,
    "time": 0,
    "venueAddress": 0,
    "bridePhoto": 0.181,
    "groomPhoto": 0.181,
    "message": 0.219,
    "blessings": 0.234,
    "dressCode": 0.264,
    "events": 0.294,
    "travel": 0.371,
    "story": 0.454,
    "galleryImages": 0.486,
    "musicUrl": 0.486,
    "faq": 0.577,
    "contacts": 0.597,
    "whatsappNumber": 0.597,
    "rsvpBy": 0.696,
    "hashtag": 0.771,
    "livestreamUrl": 0.771,
    "registryUrl": 0.771
  },
  "signature-kalyanam": {
    "invocation": 0,
    "brideName": 0,
    "groomName": 0,
    "date": 0,
    "time": 0,
    "venue": 0,
    "venueAddress": 0,
    "mapsUrl": 0,
    "message": 0.108,
    "couplePhoto": 0.119,
    "bridePhoto": 0.175,
    "brideParents": 0.203,
    "groomPhoto": 0.214,
    "groomParents": 0.242,
    "blessings": 0.265,
    "events": 0.312,
    "story": 0.386,
    "galleryImages": 0.429,
    "musicUrl": 0.429,
    "dressCode": 0.549,
    "travel": 0.592,
    "contacts": 0.625,
    "whatsappNumber": 0.625,
    "faq": 0.654,
    "rsvpBy": 0.7,
    "hashtag": 0.797,
    "livestreamUrl": 0.797
  },
  "signature-nikah": {
    "invocation": 0,
    "brideName": 0,
    "groomName": 0,
    "date": 0,
    "time": 0,
    "venue": 0,
    "venueAddress": 0,
    "mapsUrl": 0,
    "couplePhoto": 0.131,
    "message": 0.195,
    "bridePhoto": 0.206,
    "brideParents": 0.235,
    "groomPhoto": 0.249,
    "groomParents": 0.279,
    "blessings": 0.3,
    "events": 0.367,
    "story": 0.453,
    "galleryImages": 0.503,
    "musicUrl": 0.503,
    "dressCode": 0.609,
    "travel": 0.625,
    "contacts": 0.644,
    "whatsappNumber": 0.644,
    "faq": 0.677,
    "rsvpBy": 0.719,
    "hashtag": 0.789,
    "livestreamUrl": 0.789
  },
  "signature-rajwada": {
    "invocation": 0,
    "brideName": 0,
    "groomName": 0,
    "date": 0,
    "time": 0,
    "venue": 0,
    "message": 0.107,
    "couplePhoto": 0.118,
    "bridePhoto": 0.167,
    "brideParents": 0.205,
    "groomPhoto": 0.214,
    "groomParents": 0.252,
    "blessings": 0.272,
    "events": 0.328,
    "story": 0.39,
    "galleryImages": 0.428,
    "musicUrl": 0.428,
    "venueAddress": 0.549,
    "mapsUrl": 0.549,
    "dressCode": 0.56,
    "travel": 0.604,
    "contacts": 0.65,
    "whatsappNumber": 0.65,
    "faq": 0.684,
    "rsvpBy": 0.72,
    "hashtag": 0.809,
    "livestreamUrl": 0.809
  }
}
