import type { TemplateConfig } from '@/types'

export interface TemplateData {
  id: string
  name: string
  description?: string
  category?: string
  config: TemplateConfig
}

const WEDDING_FIELDS: TemplateConfig['fields'] = [
  { key: 'brideName', label: "Bride's Name", type: 'text', required: true, placeholder: 'Priya' },
  { key: 'bridePhoto', label: "Bride's Photo", type: 'image', placeholder: '' },
  { key: 'groomName', label: "Groom's Name", type: 'text', required: true, placeholder: 'Arjun' },
  { key: 'groomPhoto', label: "Groom's Photo", type: 'image', placeholder: '' },
  { key: 'date', label: 'Wedding Date', type: 'date', required: true },
  { key: 'time', label: 'Ceremony Time', type: 'time', required: true },
  { key: 'venue', label: 'Venue Name', type: 'text', required: true, placeholder: 'The Royal Palace' },
  { key: 'venueAddress', label: 'Venue Address', type: 'text', placeholder: '12 MG Road, Bengaluru' },
  { key: 'mapsUrl', label: 'Google Maps Link', type: 'url', placeholder: 'https://maps.google.com/...' },
  { key: 'dressCode', label: 'Dress Code', type: 'text', placeholder: 'Traditional Indian Attire' },
  { key: 'schedule', label: 'Event Schedule', type: 'textarea', placeholder: 'Baraat - 6:00 PM\nVarmala - 7:00 PM\nPheras - 8:00 PM' },
  { key: 'galleryImages', label: 'Gallery Image URLs', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
  { key: 'musicUrl', label: 'Background Music URL', type: 'url', placeholder: 'https://example.com/music.mp3' },
  { key: 'message', label: 'Personal Message', type: 'textarea', placeholder: 'With the blessings of our families, we joyfully invite you.' },
]

// ─── Animated 3D greeting templates (shared field set, themed per occasion) ──
const GREETING_FIELDS: TemplateConfig['fields'] = [
  { key: 'recipientName', label: "Their Name", type: 'text', required: true, placeholder: 'Ananya' },
  { key: 'senderName', label: 'Your Name', type: 'text', required: true, placeholder: 'Rohan' },
  { key: 'headline', label: 'Big Headline', type: 'text', required: true, placeholder: 'I Love You' },
  { key: 'subtitle', label: 'Subtitle (optional)', type: 'text', placeholder: 'today, tomorrow, always' },
  { key: 'photo', label: 'Cover Photo (optional)', type: 'image', placeholder: '' },
  { key: 'date', label: 'Special Date (optional)', type: 'date' },
  { key: 'galleryImages', label: 'Photo Memories (add several)', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
  { key: 'reasons', label: 'Reasons / little notes (one per line)', type: 'textarea', placeholder: "You make me laugh like no one else\nYou never gave up on us\nYou feel like home" },
  { key: 'message', label: 'Your Message', type: 'textarea', placeholder: 'Write something from the heart…' },
  { key: 'musicUrl', label: 'Background Music URL', type: 'url', placeholder: 'https://example.com/music.mp3' },
]

interface GreetingSeed { key: string; name: string; description: string; headline: string; subtitle: string; message: string; reasons: string; date?: string }

const GREETING_SEEDS: GreetingSeed[] = [
  { key: 'love', name: 'Love — 3D Journey of Hearts', description: 'A dreamy 3D sky of floating hearts, photo memories and a love confession.',
    headline: 'I Love You', subtitle: 'today, tomorrow, always', message: 'Every day with you feels like a gift I never knew I was waiting for. Thank you for being my favourite person, my safe place, and my greatest adventure.',
    reasons: 'The way you laugh at your own jokes\nHow you make ordinary days feel special\nYou always know exactly what to say\nYou believed in me before I did\nYou feel like home' },
  { key: 'valentine', name: "Valentine's Day — Floating Hearts", description: 'A romantic animated 3D valentine with photo memories and a heartfelt love note.',
    headline: "Happy Valentine's Day", subtitle: 'Be mine, forever', message: "Of all the hearts in the world, yours is the one I want to hold. Thank you for being my person. Happy Valentine's Day, my love.",
    reasons: 'Your smile is my favourite view\nYou make me a better person\nEvery day is better with you in it\nI still get butterflies\nYou are my forever valentine' },
  { key: 'anniversary', name: 'Anniversary — 3D Celebration', description: 'Celebrate your years together with animated hearts, photos and reasons you love them.',
    headline: 'Happy Anniversary', subtitle: 'to a love that keeps growing', message: 'Another year, another thousand reasons to love you more. Thank you for choosing us, every single day. Here is to forever — then, now, and always.',
    reasons: 'We turned a house into a home\nYou still make me laugh every day\nWe survived the hard days together\nYou are my best friend\nI would choose you all over again' },
  { key: 'propose', name: 'Proposal — Will You Marry Me?', description: 'An interactive 3D proposal with rings, photo memories and a "Say Yes" moment.',
    headline: 'Will You Marry Me?', subtitle: 'I want all my forevers with you', message: 'From the moment I met you, I knew. You are my calm, my chaos, my adventure, my home. I cannot imagine a single tomorrow without you in it. So, my love…',
    reasons: 'You make me feel truly seen\nEvery day with you is my favourite\nYou are my safe place\nI want to build a life with you\nForever still would not be enough' },
  { key: 'promise', name: 'Promise — A Vow in 3D', description: 'A serene animated card with photos to make a heartfelt promise.',
    headline: 'My Promise to You', subtitle: 'sealed with all my heart', message: 'I promise to stand by you, to choose you on the good days and the hard ones, and to keep loving you through it all.',
    reasons: 'I promise to always listen\nI promise to grow with you\nI promise to be your calm\nI promise to never stop trying\nI promise forever' },
  { key: 'sorry', name: 'Sorry — Healing Petals', description: 'A gentle, animated apology with soft petals, photos and a heartfelt note.',
    headline: "I'm Sorry", subtitle: 'you mean everything to me', message: 'I know I hurt you, and I am truly sorry. You matter more to me than being right ever could. I am not perfect, but I am trying — because you are worth it.',
    reasons: 'I hear you, truly\nYour feelings matter to me\nI never meant to hurt you\nYou deserve so much better\nI will do better, I promise' },
  { key: 'congratulations', name: 'Congratulations — Confetti Burst', description: 'A celebratory 3D confetti card with photos for wins, promotions and milestones.',
    headline: 'Congratulations!', subtitle: 'you absolutely earned this', message: 'You worked so hard for this and it shows in every single detail. So proud of you — go celebrate, you deserve every bit of it and so much more!',
    reasons: 'You never stopped believing\nYou earned every bit of this\nYour hard work paid off\nYou inspire everyone around you\nThe best is yet to come' },
  { key: 'festival', name: 'Festival Wishes — Glowing Diyas', description: 'Warm animated festival greetings with glowing 3D diyas and photos.',
    headline: 'Happy Diwali', subtitle: 'may your year glow bright', message: 'Wishing you and your family a festival overflowing with light, laughter, sweets, and endless joy. May this year be your brightest yet.',
    reasons: 'May your home be full of light\nMay your year be full of joy\nMay every wish come true\nMay laughter fill your days\nWith love, this festive season' },
  { key: 'family', name: 'Family Wishes — With Love', description: 'A heartfelt animated card with photos for the people who raised you.',
    headline: 'To My Family', subtitle: 'my forever, my home', message: 'Thank you for the love, the lessons, the sacrifices, and every little moment in between. I am who I am because of you, and I am endlessly grateful.',
    reasons: 'You taught me everything I know\nYou never stopped believing in me\nHome is wherever you are\nYour love shaped my whole life\nI am so grateful for you' },
  { key: 'friendship', name: 'Friendship — Starry Cheers', description: 'A playful 3D star-filled card with photos to celebrate your best friends.',
    headline: 'Happy Friendship Day', subtitle: "here's to us", message: 'Through every high, every low, and every ridiculous inside joke — I am so lucky to call you my best friend. Thank you for being my person.',
    reasons: 'You always show up for me\nYou know all my secrets\nOur inside jokes are unmatched\nYou make everything more fun\nBest friends, forever' },
]

const GALLERY_SAMPLE = 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80\nhttps://images.unsplash.com/photo-1516589091380-5d8e87df6999?auto=format&fit=crop&w=800&q=80\nhttps://images.unsplash.com/photo-1503516459261-40c66117780a?auto=format&fit=crop&w=800&q=80\nhttps://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80'

function buildGreetings(): TemplateData[] {
  return GREETING_SEEDS.map((s) => ({
    id: `greeting-${s.key}`,
    name: s.name,
    description: s.description,
    category: 'greeting',
    config: {
      fields: GREETING_FIELDS,
      defaultData: {
        recipientName: 'Ananya', senderName: 'Rohan',
        headline: s.headline, subtitle: s.subtitle, message: s.message,
        reasons: s.reasons, galleryImages: GALLERY_SAMPLE,
        photo: '', date: s.date ?? '', musicUrl: '',
      },
    },
  }))
}

export const TEMPLATES: TemplateData[] = [
  {
    id: 'elegant-wedding',
    name: 'Elegant Wedding',
    description: 'Warm ivory & gold — a timeless, romantic Indian wedding invite.',
    category: 'wedding',
    config: {
      fields: [
        { key: 'brideName', label: "Bride's Name", type: 'text', required: true, placeholder: 'Emily' },
        { key: 'bridePhoto', label: "Bride's Photo", type: 'image', placeholder: '' },
        { key: 'groomName', label: "Groom's Name", type: 'text', required: true, placeholder: 'James' },
        { key: 'groomPhoto', label: "Groom's Photo", type: 'image', placeholder: '' },
        { key: 'date', label: 'Wedding Date', type: 'date', required: true },
        { key: 'time', label: 'Ceremony Time', type: 'time', required: true },
        { key: 'venue', label: 'Venue Name', type: 'text', required: true, placeholder: 'The Grand Ballroom' },
        { key: 'venueAddress', label: 'Venue Address', type: 'text', placeholder: '123 Rose Garden Lane, New York' },
        { key: 'mapsUrl', label: 'Google Maps Link', type: 'url', placeholder: 'https://maps.google.com/...' },
        { key: 'dressCode', label: 'Dress Code', type: 'text', placeholder: 'Black Tie Optional' },
        { key: 'schedule', label: 'Event Schedule', type: 'textarea', placeholder: 'Welcome drinks - 6:00 PM\nCeremony - 7:00 PM\nDinner - 8:30 PM' },
        { key: 'galleryImages', label: 'Gallery Image URLs', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
        { key: 'musicUrl', label: 'Background Music URL', type: 'url', placeholder: 'https://example.com/music.mp3' },
        { key: 'message', label: 'Personal Message', type: 'textarea', placeholder: 'Together with our families, we joyfully invite you.' },
      ],
      defaultData: {
        brideName: 'Emily', groomName: 'James', date: '', time: '18:00',
        venue: 'The Grand Ballroom', venueAddress: '123 Rose Garden Lane, New York', mapsUrl: '',
        dressCode: 'Black Tie Optional', schedule: 'Welcome drinks - 6:00 PM\nCeremony - 7:00 PM\nDinner - 8:30 PM',
        galleryImages: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=900&q=80',
        musicUrl: '', message: 'Together with our families, we joyfully invite you to celebrate our wedding.',
      },
    },
  },
  {
    id: 'cinematic-night',
    name: 'Cinematic Night',
    description: 'Dark, dramatic & cinematic — a bold film-noir wedding experience.',
    category: 'wedding',
    config: {
      fields: WEDDING_FIELDS,
      defaultData: {
        brideName: 'Ananya', groomName: 'Vihaan', date: '', time: '19:30',
        venue: 'The Imperial Ballroom', venueAddress: '5 Grand Avenue, Mumbai', mapsUrl: '',
        dressCode: 'Black Tie', schedule: 'Cocktail Hour - 6:00 PM\nCeremony - 7:30 PM\nDinner & Dancing - 9:00 PM',
        galleryImages: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=900&q=80',
        musicUrl: '', message: 'Two souls, one beautiful story. Join us as we begin our forever.',
      },
    },
  },
  {
    id: 'indian-wedding',
    name: 'Shaadi — Indian Wedding',
    description: 'Vibrant crimson & gold — a grand cinematic Indian wedding invite.',
    category: 'wedding',
    config: {
      fields: WEDDING_FIELDS,
      defaultData: {
        brideName: 'Priya', groomName: 'Arjun', date: '', time: '18:30',
        venue: 'The Leela Palace', venueAddress: '23 Old Airport Road, Bengaluru',
        mapsUrl: '', dressCode: 'Indian Traditional / Ethnic',
        schedule: 'Baraat Arrival - 6:00 PM\nVarmala Ceremony - 7:00 PM\nSaat Pheras - 8:00 PM\nDinner & Celebrations - 9:30 PM',
        galleryImages: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1591604021695-0c69b7c05981?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1602673221577-0b56d7ce446b?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=900&q=80',
        musicUrl: '', message: 'With the blessings of the Almighty and our families, we invite you to witness our union.',
      },
    },
  },
  {
    id: 'indian-engagement',
    name: 'Mangni — Engagement',
    description: 'Rose gold & plum — a romantic Indian ring ceremony invitation.',
    category: 'engagement',
    config: {
      fields: [
        { key: 'partner1Name', label: "Bride's Name", type: 'text', required: true, placeholder: 'Meera' },
        { key: 'partner1Photo', label: "Bride's Photo", type: 'image', placeholder: '' },
        { key: 'partner2Name', label: "Groom's Name", type: 'text', required: true, placeholder: 'Rohan' },
        { key: 'partner2Photo', label: "Groom's Photo", type: 'image', placeholder: '' },
        { key: 'date', label: 'Engagement Date', type: 'date', required: true },
        { key: 'time', label: 'Ceremony Time', type: 'time', required: true },
        { key: 'venue', label: 'Venue Name', type: 'text', required: true, placeholder: 'Taj Falaknuma Palace' },
        { key: 'venueAddress', label: 'Venue Address', type: 'text', placeholder: 'Engine Bowli, Hyderabad' },
        { key: 'mapsUrl', label: 'Google Maps Link', type: 'url', placeholder: 'https://maps.google.com/...' },
        { key: 'dressCode', label: 'Dress Code', type: 'text', placeholder: 'Cocktail / Semi-Formal' },
        { key: 'schedule', label: 'Event Schedule', type: 'textarea', placeholder: 'Welcome Drinks - 5:00 PM\nRing Exchange - 6:30 PM\nDinner - 8:00 PM' },
        { key: 'galleryImages', label: 'Gallery Image URLs', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
        { key: 'message', label: 'Personal Message', type: 'textarea', placeholder: 'Two hearts, one promise. Join us as we begin our journey.' },
      ],
      defaultData: {
        partner1Name: 'Meera', partner2Name: 'Rohan', date: '', time: '17:00',
        venue: 'Taj Falaknuma Palace', venueAddress: 'Engine Bowli, Hyderabad',
        mapsUrl: '', dressCode: 'Cocktail / Semi-Formal',
        schedule: 'Welcome Drinks - 5:00 PM\nRing Exchange Ceremony - 6:30 PM\nCelebration Dinner - 8:00 PM',
        galleryImages: 'https://images.unsplash.com/photo-1510077143771-1b6a4e2cde35?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=900&q=80',
        message: 'Two hearts, one beautiful promise. Join us as we take our first step towards forever.',
      },
    },
  },
  {
    id: 'indian-birthday',
    name: 'Janamdin — Birthday',
    description: 'Saffron & indigo — a vibrant Bollywood birthday celebration.',
    category: 'birthday',
    config: {
      fields: [
        { key: 'celebrantName', label: "Celebrant's Name", type: 'text', required: true, placeholder: 'Kavya' },
        { key: 'celebrantPhoto', label: "Celebrant's Photo", type: 'image', placeholder: '' },
        { key: 'age', label: 'Turning Age (optional)', type: 'text', placeholder: '25' },
        { key: 'date', label: 'Birthday Date', type: 'date', required: true },
        { key: 'time', label: 'Party Time', type: 'time', required: true },
        { key: 'venue', label: 'Venue Name', type: 'text', required: true, placeholder: 'The Oberoi Grand' },
        { key: 'venueAddress', label: 'Venue Address', type: 'text', placeholder: '15 Jawaharlal Nehru Road, Kolkata' },
        { key: 'mapsUrl', label: 'Google Maps Link', type: 'url', placeholder: 'https://maps.google.com/...' },
        { key: 'theme', label: 'Party Theme', type: 'text', placeholder: 'Bollywood Glam' },
        { key: 'schedule', label: 'Party Schedule', type: 'textarea', placeholder: 'Cocktails - 7:00 PM\nDinner - 8:00 PM\nCake Cutting - 9:30 PM' },
        { key: 'galleryImages', label: 'Gallery Image URLs', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
        { key: 'musicUrl', label: 'Background Music URL', type: 'url', placeholder: 'https://example.com/music.mp3' },
        { key: 'message', label: 'Personal Message', type: 'textarea', placeholder: "Life's a party — come celebrate with me!" },
      ],
      defaultData: {
        celebrantName: 'Kavya', age: '25', date: '', time: '19:00',
        venue: 'The Oberoi Grand', venueAddress: '15 Jawaharlal Nehru Road, Kolkata',
        mapsUrl: '', theme: 'Bollywood Glam',
        schedule: 'Cocktail Hour - 7:00 PM\nDinner - 8:00 PM\nCake Cutting - 9:30 PM\nDance Floor Opens - 10:00 PM',
        galleryImages: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=900&q=80',
        musicUrl: '', message: "Life is a beautiful journey — come add sparkle to mine on my special day!",
      },
    },
  },
  {
    id: 'griha-pravesh',
    name: 'Griha Pravesh — House Warming',
    description: 'Turmeric & terracotta — a sacred Griha Pravesh ceremony invite.',
    category: 'housewarming',
    config: {
      fields: [
        { key: 'hostNames', label: 'Host Names', type: 'text', required: true, placeholder: 'Sharma Family' },
        { key: 'hostPhoto', label: 'Family Photo', type: 'image', placeholder: '' },
        { key: 'date', label: 'Ceremony Date', type: 'date', required: true },
        { key: 'time', label: 'Muhurat Time', type: 'time', required: true },
        { key: 'venue', label: 'New Home Address', type: 'text', required: true, placeholder: 'Flat 4B, Lotus Residency' },
        { key: 'venueAddress', label: 'Full Address', type: 'text', placeholder: 'Sector 62, Noida, UP 201301' },
        { key: 'mapsUrl', label: 'Google Maps Link', type: 'url', placeholder: 'https://maps.google.com/...' },
        { key: 'pooja', label: 'Pooja / Muhurat Details', type: 'text', placeholder: 'Ganesh Pooja at 9:00 AM sharp' },
        { key: 'schedule', label: 'Program Schedule', type: 'textarea', placeholder: 'Ganesh Pooja - 9:00 AM\nGriha Pravesh - 10:30 AM\nLunch Prasad - 1:00 PM' },
        { key: 'galleryImages', label: 'Gallery Image URLs', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
        { key: 'message', label: 'Personal Message', type: 'textarea', placeholder: 'With divine blessings, we warmly invite you to our new abode.' },
      ],
      defaultData: {
        hostNames: 'The Sharma Family', date: '', time: '09:00',
        venue: 'Flat 4B, Lotus Residency', venueAddress: 'Sector 62, Noida, UP 201301',
        mapsUrl: '', pooja: 'Ganesh Pooja & Vastu Pooja at 9:00 AM',
        schedule: 'Ganesh Pooja - 9:00 AM\nVastu Pooja - 10:00 AM\nGriha Pravesh Muhurat - 10:30 AM\nBhoomi Pooja & Lunch - 12:30 PM',
        galleryImages: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80',
        message: 'With the blessings of the Almighty, we humbly invite you to grace our new home.',
      },
    },
  },
  {
    id: 'namakaran',
    name: 'Namakaran — Naming Ceremony',
    description: 'Soft gold & sky — a pure and blessed naming ceremony invite.',
    category: 'naming',
    config: {
      fields: [
        { key: 'babyName', label: "Baby's Name", type: 'text', required: true, placeholder: 'Aarav' },
        { key: 'babyPhoto', label: "Baby's Photo", type: 'image', placeholder: '' },
        { key: 'babyGender', label: 'Baby Gender (Boy/Girl)', type: 'text', placeholder: 'Boy' },
        { key: 'parentNames', label: "Parents' Names", type: 'text', required: true, placeholder: 'Anjali & Suresh Kapoor' },
        { key: 'date', label: 'Ceremony Date', type: 'date', required: true },
        { key: 'time', label: 'Ceremony Time', type: 'time', required: true },
        { key: 'venue', label: 'Venue Name', type: 'text', required: true, placeholder: 'Kapoor Residence' },
        { key: 'venueAddress', label: 'Venue Address', type: 'text', placeholder: '7 Sunflower Society, Pune' },
        { key: 'mapsUrl', label: 'Google Maps Link', type: 'url', placeholder: 'https://maps.google.com/...' },
        { key: 'schedule', label: 'Program Schedule', type: 'textarea', placeholder: 'Satyanarayan Pooja - 10:00 AM\nNamakaran Ceremony - 11:30 AM\nLunch - 1:00 PM' },
        { key: 'message', label: 'Personal Message', type: 'textarea', placeholder: 'With joy in our hearts, we invite you to bless our little one.' },
      ],
      defaultData: {
        babyName: 'Aarav', babyGender: 'Boy', parentNames: 'Anjali & Suresh Kapoor',
        date: '', time: '10:00', venue: 'Kapoor Residence',
        venueAddress: '7 Sunflower Society, Baner, Pune 411045', mapsUrl: '',
        schedule: 'Satyanarayan Pooja - 10:00 AM\nNamakaran Ceremony - 11:30 AM\nBlessing Time - 12:30 PM\nLunch Prasad - 1:00 PM',
        message: 'With immense joy in our hearts, we joyfully invite you to bless our little one with your love and presence.',
      },
    },
  },
  {
    id: 'kgf-wedding',
    name: 'KGF — Royal Empire Wedding',
    description: 'Dark gold cinematic luxury — a legendary South Indian wedding invite inspired by the KGF universe.',
    category: 'movie',
    config: {
      fields: [
        ...WEDDING_FIELDS,
        { key: 'coupleStory', label: 'Couple Love Story', type: 'textarea', placeholder: 'Their story began in gold and fire. Two hearts destined for each other, forged by fate…' },
        { key: 'groomFamilyDetails', label: "Groom's Family Details", type: 'text', placeholder: "S/o Suryakumar & Kamala Devi · Bengaluru" },
        { key: 'brideFamilyDetails', label: "Bride's Family Details", type: 'text', placeholder: "D/o Rajmohan & Lakshmi Devi · Chennai" },
      ],
      defaultData: {
        groomName: 'Rocky', brideName: 'Reena', date: '', time: '19:00',
        venue: 'Kolar Gold Palace', venueAddress: 'KGF Nagar, Kolar District, Karnataka',
        mapsUrl: '', dressCode: 'Royal Indian Ethnic',
        schedule: 'Baraat Procession - 6:00 PM\nVarmala Ceremony - 7:30 PM\nSaat Pheras - 8:30 PM\nRoyal Dinner & Celebrations - 10:00 PM',
        galleryImages: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1591604021695-0c69b7c05981?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1602673221577-0b56d7ce446b?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=900&q=80',
        musicUrl: '',
        message: 'From the depths of destiny, two souls rise to reign together. Your presence honours our legacy.',
        coupleStory: 'Their story began in gold and fire. Two hearts destined for each other, forged by fate in the golden land — a love as powerful and eternal as the mountains themselves.',
        groomFamilyDetails: 'S/o Suryakumar & Kamala Devi · Bengaluru',
        brideFamilyDetails: 'D/o Rajmohan & Lakshmi Devi · Chennai',
      },
    },
  },
  {
    id: 'royal-deco',
    name: 'Royal Deco — Palace Edition',
    description: 'Midnight navy & antique gold Art Deco — a retro palace wedding invitation fit for royalty.',
    category: 'retro',
    config: {
      fields: [
        ...WEDDING_FIELDS,
        { key: 'coupleStory', label: 'Couple Love Story', type: 'textarea', placeholder: 'Their love was written in the stars long before they ever met…' },
        { key: 'groomFamilyDetails', label: "Groom's Family Details", type: 'text', placeholder: 'S/o Ramesh & Savitri Devi · Mysuru' },
        { key: 'brideFamilyDetails', label: "Bride's Family Details", type: 'text', placeholder: 'D/o Suresh & Padmavati Devi · Bengaluru' },
      ],
      defaultData: {
        groomName: 'Arjun', brideName: 'Ananya', date: '', time: '18:30',
        venue: 'The Royal Palace Banquet', venueAddress: 'Palace Road, Bengaluru, Karnataka 560001',
        mapsUrl: '', dressCode: 'Royal Indian Ethnic / Black Tie',
        schedule: 'Royal Reception - 6:00 PM\nVarmala Ceremony - 7:00 PM\nSaat Pheras - 8:00 PM\nGrand Dinner - 9:30 PM',
        galleryImages: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=900&q=80',
        musicUrl: '',
        message: 'Together with our families, we joyfully invite you to witness our union and share in our joy.',
        coupleStory: 'Their love was written in the stars long before they ever met — two souls destined by fate, bound by gold, and united for eternity.',
        groomFamilyDetails: 'S/o Ramesh & Savitri Devi · Mysuru',
        brideFamilyDetails: 'D/o Suresh & Padmavati Devi · Bengaluru',
      },
    },
  },
  {
    id: 'anniversary',
    name: 'Saalgirah — Anniversary',
    description: 'Deep wine & gold — an eternal anniversary celebration.',
    category: 'anniversary',
    config: {
      fields: [
        { key: 'coupleNames', label: "Couple's Names", type: 'text', required: true, placeholder: 'Sunita & Rajesh' },
        { key: 'couplePhoto', label: "Couple's Photo", type: 'image', placeholder: '' },
        { key: 'years', label: 'Years Together', type: 'text', placeholder: '25' },
        { key: 'date', label: 'Anniversary Date', type: 'date', required: true },
        { key: 'time', label: 'Event Time', type: 'time', required: true },
        { key: 'venue', label: 'Venue Name', type: 'text', required: true, placeholder: 'ITC Grand Maratha' },
        { key: 'venueAddress', label: 'Venue Address', type: 'text', placeholder: 'Sahar, Mumbai 400099' },
        { key: 'mapsUrl', label: 'Google Maps Link', type: 'url', placeholder: 'https://maps.google.com/...' },
        { key: 'dressCode', label: 'Dress Code', type: 'text', placeholder: 'Formal / Indian Ethnic' },
        { key: 'schedule', label: 'Event Schedule', type: 'textarea', placeholder: 'Welcome - 7:00 PM\nDinner - 8:30 PM\nCake Cutting - 10:00 PM' },
        { key: 'galleryImages', label: 'Gallery Image URLs', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
        { key: 'musicUrl', label: 'Background Music URL', type: 'url', placeholder: 'https://example.com/music.mp3' },
        { key: 'message', label: 'Personal Message', type: 'textarea', placeholder: 'A journey of love, laughter and togetherness.' },
      ],
      defaultData: {
        coupleNames: 'Sunita & Rajesh', years: '25', date: '', time: '19:00',
        venue: 'ITC Grand Maratha', venueAddress: 'Sahar, Andheri East, Mumbai 400099',
        mapsUrl: '', dressCode: 'Formal / Indian Ethnic',
        schedule: 'Cocktail Reception - 7:00 PM\nGala Dinner - 8:30 PM\nCake Cutting - 10:00 PM\nDance & Celebrations - 10:30 PM',
        galleryImages: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1516589091380-5d8e87df6999?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=900&q=80',
        musicUrl: '', message: 'Twenty-five years of love, laughter, and togetherness — and we are just getting started.',
      },
    },
  },
  {
    id: 'luxury-wedding',
    name: 'Luxury Wedding',
    description: 'Ivory, champagne & gold — a premium multi-ceremony Indian wedding invitation.',
    category: 'wedding',
    config: {
      fields: [
        { key: 'brideName', label: "Bride's Name", type: 'text', required: true, placeholder: 'Priya' },
        { key: 'bridePhoto', label: "Bride's Photo", type: 'image', placeholder: '' },
        { key: 'groomName', label: "Groom's Name", type: 'text', required: true, placeholder: 'Arjun' },
        { key: 'groomPhoto', label: "Groom's Photo", type: 'image', placeholder: '' },
        { key: 'date', label: 'Wedding Date', type: 'date', required: true },
        { key: 'time', label: 'Wedding Time', type: 'time', required: true },
        { key: 'venue', label: 'Wedding Venue', type: 'text', required: true, placeholder: 'The Leela Palace' },
        { key: 'venueAddress', label: 'Venue Address', type: 'text', placeholder: '23 Old Airport Road, Bengaluru' },
        { key: 'mapsUrl', label: 'Google Maps Link', type: 'url', placeholder: 'https://maps.google.com/...' },
        { key: 'mehendiDate', label: 'Mehendi Date', type: 'date' },
        { key: 'mehendiTime', label: 'Mehendi Time', type: 'time' },
        { key: 'mehendiVenue', label: 'Mehendi Venue', type: 'text', placeholder: 'Bride\'s Home' },
        { key: 'haldiDate', label: 'Haldi Date', type: 'date' },
        { key: 'haldiTime', label: 'Haldi Time', type: 'time' },
        { key: 'haldiVenue', label: 'Haldi Venue', type: 'text', placeholder: 'Bride\'s Home' },
        { key: 'sangeetDate', label: 'Sangeet Date', type: 'date' },
        { key: 'sangeetTime', label: 'Sangeet Time', type: 'time' },
        { key: 'sangeetVenue', label: 'Sangeet Venue', type: 'text', placeholder: 'Banquet Hall' },
        { key: 'receptionDate', label: 'Reception Date', type: 'date' },
        { key: 'receptionTime', label: 'Reception Time', type: 'time' },
        { key: 'receptionVenue', label: 'Reception Venue', type: 'text', placeholder: 'The Grand Ballroom' },
        { key: 'brideFamily', label: "Bride's Family (one per line)", type: 'textarea', placeholder: 'Ramesh & Sunita Sharma\nUncle Vijay & Aunt Meera' },
        { key: 'groomFamily', label: "Groom's Family (one per line)", type: 'textarea', placeholder: 'Suresh & Kavita Verma\nUncle Anand & Aunt Rekha' },
        { key: 'galleryImages', label: 'Gallery Image URLs', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
        { key: 'musicUrl', label: 'Background Music URL', type: 'url', placeholder: 'https://example.com/music.mp3' },
        { key: 'message', label: 'Personal Message', type: 'textarea', placeholder: 'With the blessings of our families, we joyfully invite you.' },
      ],
      defaultData: {
        brideName: 'Priya', groomName: 'Arjun', date: '', time: '18:30',
        venue: 'The Leela Palace', venueAddress: '23 Old Airport Road, Bengaluru 560008',
        mapsUrl: '',
        mehendiDate: '', mehendiTime: '16:00', mehendiVenue: "Bride's Residence",
        haldiDate: '', haldiTime: '10:00', haldiVenue: "Bride's Residence",
        sangeetDate: '', sangeetTime: '19:00', sangeetVenue: 'Palace Banquet Hall',
        receptionDate: '', receptionTime: '19:30', receptionVenue: 'The Grand Ballroom',
        brideFamily: '', groomFamily: '',
        galleryImages: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1591604021695-0c69b7c05981?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1602673221577-0b56d7ce446b?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=900&q=80',
        musicUrl: '',
        message: 'With the blessings of the Almighty and our families, we joyfully invite you to witness our union.',
      },
    },
  },
  {
    id: 'surprise-journey',
    name: '3D Surprise Journey',
    description: 'An interactive 3D gift they unlock — secret PIN, photo memories, balloon pops, a sliding puzzle, a scratch card and a handwritten letter.',
    category: 'interactive',
    config: {
      fields: [
        // ── The people (Step 2) ──
        { key: 'recipientName', label: "Their Name", type: 'text', required: true, placeholder: 'Ananya' },
        { key: 'senderName', label: 'Your Name', type: 'text', required: true, placeholder: 'Rohan' },
        { key: 'occasion', label: 'Occasion / Greeting', type: 'text', required: true, placeholder: 'Happy Birthday' },
        { key: 'coverMessage', label: 'Gift Tag Line', type: 'text', placeholder: 'A little something for you…' },
        // ── The unlock (Step 3) ──
        { key: 'pin', label: 'Secret PIN (3–6 digits)', type: 'text', required: true, placeholder: '2601' },
        { key: 'pinHint', label: 'PIN Hint', type: 'text', placeholder: 'The day we first met 💕' },
        // ── Photos + puzzle share the same gallery (Step 4) ──
        { key: 'galleryImages', label: 'Photo Memories', type: 'textarea', placeholder: 'Paste image URLs, one per line' },
        // ── Interactive touches (Step 4) ──
        { key: 'balloonMessages', label: 'Balloon Messages (one per line)', type: 'textarea', placeholder: "You make me smile\nMy favourite person\nHere's to us 🥂" },
        { key: 'scratchMessage', label: 'Scratch Card Reveal', type: 'textarea', placeholder: 'You + Me = Forever ❤️' },
        { key: 'letterBody', label: 'Handwritten Letter', type: 'textarea', placeholder: 'Dear Ananya,\n\nFrom the day we met, everything changed…' },
        { key: 'signature', label: 'Letter Signature', type: 'text', placeholder: 'Forever yours, Rohan' },
        { key: 'musicUrl', label: 'Background Music URL', type: 'url', placeholder: 'https://example.com/music.mp3' },
      ],
      defaultData: {
        recipientName: 'Ananya',
        senderName: 'Rohan',
        occasion: 'Happy Birthday',
        coverMessage: 'A little something I made just for you…',
        pin: '2601',
        pinHint: 'The day we first met 💕 (DDMM)',
        galleryImages: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1516589091380-5d8e87df6999?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80\nhttps://images.unsplash.com/photo-1503516459261-40c66117780a?auto=format&fit=crop&w=900&q=80',
        balloonMessages: 'You make every day brighter\nMy favourite person in the world\nThank you for being you\nHere\'s to many more 🥂',
        scratchMessage: 'You + Me = Forever ❤️',
        letterBody: 'Dear Ananya,\n\nFrom the very first day we met, everything in my world got a little brighter. This tiny gift is just my way of saying what words never quite capture — that I am so grateful for you.\n\nHappy birthday, my love. Here is to us, and to every adventure still waiting.',
        signature: 'Forever yours, Rohan',
        musicUrl: '',
      },
    },
  },
  ...buildGreetings(),
]

export function getTemplateData(id: string): TemplateData | undefined {
  return TEMPLATES.find((t) => t.id === id)
}
